# Generated by Django 4.0.10 on 2023-06-25 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frequencias', '0001_initial'),
        ('users', '0002_projeto_proreitor_orientador_coordenador_campus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordenador',
            name='campus',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='frequencias.campus'),
        ),
        migrations.AlterField(
            model_name='bolsista',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bolsistas', to='frequencias.campus'),
        ),
        migrations.AlterField(
            model_name='bolsista',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bolsistas', to='frequencias.projeto'),
        ),
        migrations.DeleteModel(
            name='Campus',
        ),
        migrations.DeleteModel(
            name='Projeto',
        ),
    ]
