# Generated by Django 4.0.10 on 2023-06-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frequencias', '0002_ponto_alter_campus_options_alter_projeto_options_and_more'),
        ('users', '0003_coordenador_campus_alter_bolsista_campus_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bolsista',
            options={'verbose_name': 'Bolsista', 'verbose_name_plural': 'Bolsistas'},
        ),
        migrations.AlterModelOptions(
            name='coordenador',
            options={'verbose_name': 'Coordenador', 'verbose_name_plural': 'Coordenadores'},
        ),
        migrations.AlterModelOptions(
            name='orientador',
            options={'verbose_name': 'Orientador', 'verbose_name_plural': 'Orientadores'},
        ),
        migrations.AlterModelOptions(
            name='proreitor',
            options={'verbose_name': 'Pro-reitor', 'verbose_name_plural': 'Pro-reitores'},
        ),
        migrations.AddField(
            model_name='bolsista',
            name='frequencias',
            field=models.ManyToManyField(related_name='bolsista', to='frequencias.frequencia'),
        ),
    ]
