# Generated by Django 4.0.10 on 2023-06-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frequencias', '0002_ponto_alter_campus_options_alter_projeto_options_and_more'),
        ('users', '0004_alter_bolsista_options_alter_coordenador_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolsista',
            name='pontos',
            field=models.ManyToManyField(blank=True, related_name='bolsista', to='frequencias.ponto'),
        ),
        migrations.AlterField(
            model_name='bolsista',
            name='frequencias',
            field=models.ManyToManyField(blank=True, related_name='bolsista', to='frequencias.frequencia'),
        ),
    ]
