# Generated by Django 4.0.10 on 2023-06-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_bolsista_pontos_alter_bolsista_frequencias'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='matricula',
            field=models.CharField(default=0, max_length=150),
        ),
    ]
