# Generated by Django 4.0.10 on 2023-06-25 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolsista',
            name='orientador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bolsistas', to='users.orientador'),
        ),
    ]
