# Generated by Django 4.0.10 on 2023-06-26 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_bolsista_pontos_bolsista_pontos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bolsista',
            name='pontos',
        ),
    ]
