# Generated by Django 4.0.10 on 2023-06-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frequencias', '0005_remove_frequencia_pontos_ponto_bolsista_and_more'),
        ('users', '0010_orientador_campus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolsista',
            name='frequencias',
            field=models.ManyToManyField(blank=True, to='frequencias.frequencia'),
        ),
    ]
