# Generated by Django 4.0.10 on 2023-06-26 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_bolsista_frequencias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bolsista',
            name='frequencias',
        ),
    ]
