# Generated by Django 4.0.10 on 2023-09-17 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frequencias', '0006_frequencia_bolsista'),
        ('users', '0012_remove_bolsista_frequencias'),
    ]

    operations = [
        migrations.AddField(
            model_name='orientador',
            name='projeto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orientadores', to='frequencias.projeto'),
        ),
    ]
