# Generated by Django 4.0.10 on 2023-06-26 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_bolsista_orientador'),
        ('frequencias', '0002_ponto_alter_campus_options_alter_projeto_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='coordenador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to='users.orientador'),
        ),
    ]
