# Generated by Django 4.0.10 on 2023-06-26 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_bolsista_pontos'),
        ('frequencias', '0004_alter_frequencia_ch_total_alter_frequencia_pontos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frequencia',
            name='pontos',
        ),
        migrations.AddField(
            model_name='ponto',
            name='bolsista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pontos', to='users.bolsista'),
        ),
        migrations.AddField(
            model_name='ponto',
            name='frequencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pontos', to='frequencias.frequencia'),
        ),
    ]
