# Generated by Django 4.0.10 on 2023-06-26 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_bolsista_frequencias'),
        ('frequencias', '0005_remove_frequencia_pontos_ponto_bolsista_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequencia',
            name='bolsista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frequencias', to='users.bolsista'),
        ),
    ]
